PPBDS/primer

_output.yml
index.Rmd

Added comments on output options

---

TODO.txt

This should be working, check Line 3 of TODO.txt. The commit showed that there were a bunch of changes, but that's just because I added empty lines and messed up the order. There shouldn't be any major changes though.

Edited TODO.txt in order to test pull request.

---

03-data.Rmd
TODO.txt

I created my comments for Chapter 3 Data in the Primer Textbook.

AG Ch 3 Data Comments

---

03-data.Rmd
tools.Rmd

I finished the changes that we discussed in our meeting earlier today. I wrote the changes directly into the file this time rather than just in the comments, and I managed to resolve most of the issues.

AG Chapter 3 Data

---

TODO.txt

Add name "Yuhan Wu" in TODO.txt

Add Name in TODO.txt

---

TODO.txt

Let me know if I did something incorrect, as I'm not too familiar with doing pull requests

Adding my name (Ajay) to TODO.txt.

---

TODO.txt

added name

---

TODO.txt

Adding my name to the TODO.txt file, as per your instructions :)

adding name to TODO doc

---

05-probability.Rmd

Adding Comments on Chapter 5-Probability.

Chapter 5 primer

---

01-visualization.Rmd

Updated visualiaztion.Rmd

---

00-getting-started.Rmd

Changed a few wording which I thought would be better.

Updated Getting Started

---

02-wrangling.Rmd

nuking from orbit was a success

more comments and reformatting that i wanted to do yesterday

---

python.Rmd

Moreover, added a few commends for the Preceptor to be able to knit this file.

Added the getting started section

---

05-probability.Rmd

These are just graphs, will add explanations on a weekend. I change the Posterior graph using rep() instead of rnorm like the mathematical and empirical.

Add graph for Height

---

05-probability.Rmd

Add some word explanation for heights, draft number 1, planning on changing some words to make better tmr if have time.

Word explanation for heights.

---

python.Rmd

Fixed the code chunk about producing error.

Fixed the minor change Preceptor proposed

---

05-probability.Rmd

It says that I have a conflict in the file, did I resolve it already or something else?

Work for today + conflicts again?

---

05-probability.Rmd

The movie clip doesn't seem to work on my end, but I copy the exact same code from chap.6, trying to fix.

Add population paragrah+ movie clip

---

05-probability.Rmd

I did not include the formula for presidential election.

Add Latex to coin, dice and height

---

02-wrangling.Rmd

I've also added a note to one of the changes that I wasn't sure about, in the "scaling a distribution" section. I would appreciate it if you could double-check it, Preceptor.

Updated sections 2.8,2.9,2.10

---

TODO.txt

inital update

---

08-three-parameters.qmd

only committed qmd file after rendering page

updates to chapter 5: income ~ age & liberal ~ income
